### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by aryopg** [mhaghighat/gabor#1]
I find that your code is really good. It is exactly what i'm searching for. But the problem is, i'm not really good at translating it into python. I really want to find the python version of gabor filter feature extraction. Is there any suggestion from you? thanks

**Comment by mhaghighat** [comment]
Hi,

I am not an expert in Python either. Apparently, there is a MATLAB Engine
API for Python that might be useful for you to call the MATLAB function
inside your Python script. Please see the following link:
http://www.mathworks.com/help/matlab/matlab-engine-for-python.html

I hope it helps.

Mohammad

**Comment by aryopg** [comment]
I think i can make the python code already, now i would like to ask what kind of algorithm that i should use if i want to match the gabor feature vector of one image to another?

**Comment by mhaghighat** [comment]
You can use any classifier such as minimum distance, KNN, SVM, SRC, etc.

**Comment by aryopg** [comment]
Can i use it in a CBIR machine? And is there any example on how to
implement it using feature vectors?

**Comment by aryopg** [comment]
And one more, when i tried to run my code that was translated from your
code. I got a result of 5*8 orientation, but with not so much differences
between each image. What do you think was wrong in my code? i've translated
it until the feature vector extraction, and got that result

**Comment by mhaghighat** [comment]
I believe you can, because they have used it before.
See the two papers attached.

**Comment by mhaghighat** [comment]
I have no idea!
I am sorry.
