### ISSUE TITLE
Need to show the combine output

### ISSUE THREAD

**Issue by nashraraza** [mhaghighat/gabor#3]
Hey there!
Can you help me out please, if I need to show the output filtered image and not use them as feature just show a final output with all the orientations collectively what can I do for it? is it possible

**Comment by mhaghighat** [comment]
You just need to uncomment the [lines 87 to 105 in gaborFeatures.m](https://github.com/mhaghighat/gabor/blob/cb8b3e11bb4b72bf2eafc70e9143463a91e71e0e/gaborFeatures.m#L87-L105). It will show the filtered images.
